- name: upload and deploy lambda
  uses: appleboy/lambda-action@master
    with:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_region: us-east-1
      function_name: my-function
      zip_file: lambda_bundle.zip
