name: AWS Lambda Deploy Function
# You may pin to the exact commit or the version.
# uses: zeagord/aws-lambda-deploy-function@63409e95ba826bc89e9c7ca35e4bf3922bf00090
uses: zeagord/aws-lambda-deploy-function@0.0.3
with:
  # Jar or Zip package of the lambda
  artifact: lambda_bundle.zip
  # Name of the Lambda function
  function-name: lambda_handler 
  # Runtime fo the Lambda, Java11 or Node11
  runtime: python 3.7 
  # Name of the Handler
  handler: lambda_handler 
  # AWS secret key
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # AWS secret key ID
  AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  # AWS region
  AWS_REGION: ${{ secrets.AWS_REGION }}